### ISSUE TITLE
Incompatible with Elixir 1.10?

### ISSUE THREAD

**Issue by tensiondriven** [hauleth/mix_unused#1]
```
== Compilation error in file lib/mix_unused.ex ==
** (CompileError) lib/mix_unused.ex:55: cannot import Mix.Compilers.Elixir.read_manifest/2 because it is undefined or private
    (elixir 1.10.2) src/elixir_import.erl:64: :elixir_import.calculate/6
    (elixir 1.10.2) src/elixir_import.erl:18: :elixir_import.import/4
```
@hauleth, any chance of an update?  This seems to be the only dep out there to provide dead code detection.

**Comment by hauleth** [comment]
Yes, I am planning to update to compiler traces for some time now. Maybe today I will find some time to spare.

**Comment by tensiondriven** [comment]
I would really love that.  I’ve been perplexed on an optimization issue in my project for a few days now and being able to run dead code removal would be very helpful.


Sent from my Warp Bubble
Schedule a meeting • Chat with me now

LinkedIn • YouTube • Teal Dog

**Comment by hauleth** [comment]
I have started working and I will publish the PR tomorrow. So far the implementation seems nice, a little bit cleaner in some parts but messier in others. Will see how the overall result will be.

**Comment by tensiondriven** [comment]
Thank you — I just merged a commit of about 1,100 lines that was all refactoring in an attempt to optimize (minimize) compile time dependencies, and I’m almost certain I’ve got plenty of dead code.  Would be delighted to give it a test when ready.


Sent from my Warp Bubble
Schedule a meeting • Chat with me now

LinkedIn • YouTube • Teal Dog

**Comment by cblavier** [comment]
I would love to use your project @hauleth ! 
How far are you from getting #2 completed?

**Comment by YuriiZdyrko** [comment]
Hi @hauleth!
Just letting you know that I tried running this task, and I don't get any results.
I'm working on a large codebase right now, and was given task to remove dead code.
`mix_unused` looks potentially useful.
