### ISSUE TITLE
Add option to ignore documented functions in documented modules

### ISSUE THREAD

**Issue by hauleth** [hauleth/mix_unused#10]
It can be useful for library authors, as documented functions are "naturally" exported and meant for the end user to be used. So if function is not hidden and available in not hidden module, then it can be treated as automatically exported. Hidden functions and functions in hidden modules should be treated as non-exported and there should be warning on them.

**Comment by noozo** [comment]
+1. Maybe an option to exclude based on regexp or glob? So we could, for example:
```
unused: [
  ignore: [
    "__*__"
  ]
],
```
Or something like that :)

**Comment by noozo** [comment]
I noticed it already supports regexp for function names, but a full module is still required (which would required adding all modules with the same regexp):
```
[{Foo, ~r/^ba[rz]$/}]
```
Would be nice to either pattern match on the module as well, or just have a global option to ignore `__X__` functions.

**Comment by hauleth** [comment]
It should be possible to pattern match on module as well. And you can just use "catch-all" term `:_` as module name, so ro ignore all `__X__` functions you can do:

```elixir
[{:_, ~r/^__.*__\??$/}]
```

**Comment by noozo** [comment]
Indeed, added a PR with a doctest, if that's useful: https://github.com/hauleth/mix_unused/pull/12
