### ISSUE TITLE
How to pass options to compiler (namely severity)?

### ISSUE THREAD

**Issue by noozo** [hauleth/mix_unused#13]
Looking at the code, severity is read from options, not from the project config, so putting that config alongside the ignore will also not work, right?

I trying adding a tuple in the compiler with the options inside, like this:
```
{:unused, [severity: "error"]}
```

But that doesn't seem to be supported by mix compiler. Any other way i can setup unused to fail my compilation if there are unused functions?

Thanks!

**Comment by noozo** [comment]
Figure out that you can pass the option like so
```
mix.compile --severity error
```
But that doesn't seem to make the compilation fail. Any way to do that so we could turn the lib into a CI check. That would be really useful :)

**Comment by hauleth** [comment]
I will check that out.
