### ISSUE TITLE
Suggestion: ignore predicate

### ISSUE THREAD

**Issue by hissssst** [hauleth/mix_unused#29]
First of all, this is an awesome library with high quality code inside!

### Overview

My suggestion is instead of having this code as a part of  `MixProject.project().unused.ignore` option:
```elixir
[
  {:_, :child_spec, 1},
  {:_, ~r/^__.+__\??$/, :_},
  {~r/^MyAppWeb\..*Controller/, :_, 2},
  {MyApp.Test, :foo, 1..2}
]
```

We can have a predicate closure which will look something like:
```elixir
fn
  _, :child_spec, 1 -> false,
  _, function, _ ->
    ...
end
```

But matching filter is very nice and handy, so we can have a macro which will look like:
```elixir
matching_filter([
  {:_, :child_spec, 1},
  {:_, ~r/^__.+__\??$/, :_},
  {~r/^MyAppWeb\..*Controller/, :_, 2},
  {MyApp.Test, :foo, 1..2}
])
```

And will compile list of matches into a closure

### Why

1. Closures are more flexible
2. Everybody knows how `fn` works, while matching requires some additional knowledge
3. Matching predicate compiler is too awesome to be an internal part of this project

**Comment by hauleth** [comment]
Hmm, interesting idea, however I find "match-spec like" more useful in most cases (at least for me). However I see that it can be useful to use functions there. Unfortunately the "macro" approach is not possible without moving the configuration out of the `mix.exs`. So my approach to that would be to allow unary (maybe even binary) functions in the list of the patterns, like:

```elixir
[
  {:_, :child_spec, 1},
  &match?({MyApp.Test, :foo, arity}, _ when arity in 1..2, &1)
]
```

This would give the best of two worlds. What do you think?

**Comment by hissssst** [comment]
This idea sounds nice!

**Comment by hauleth** [comment]
@hissssst #30 is something you should look at. I still need to add documentation, but it allows you to pass unary function as a matcher in the `:ignore`. My plan is to also add 2-ary functions there to allow filtering based on metadata (file, line, or `@doc` metadata), but that will probably be added later.
