### ISSUE TITLE
Possible to ignore based on folder (for instance /test)?

### ISSUE THREAD

**Issue by noozo** [hauleth/mix_unused#31]
Hi,

I found several points in my project where when i have something like 
`def some_func(arg1 \\ 1, arg2 \\ 2, arg3 \\ 3)`

And if only use `some_func(1, 2, 3)` in a test function (like a fixture or something like that) i get an unused warning. I was wondering if mix_unused is working for test code as well and, if not, if there is a way to ignore an entire folder (not modules, but really a folder).

Thanks!

**Comment by hauleth** [comment]
Not yet, but #30 should allow filtering on metadata via 2-art function and then such functionality will be possible.

**Comment by hauleth** [comment]
It will be now possible via binary predicate function. It is not documented yet, but you may track #33 for documentation. Such predicate accepts MFA as a first argument and metadata as 2nd. Metadata will contain information about path to the file.
